# Generated by Django 4.2.4 on 2023-10-25 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=50)),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('doe', models.DateField(help_text='Date of Employment', null=True)),
                ('cv_pdf', models.FileField(blank=True, help_text='Your PDF CV', upload_to='CV')),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Biochemistry', 'Biochemistry'), ('Microbiology', 'Microbiology'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry')], default='Chemistry', max_length=50)),
                ('phone', models.CharField(default='0801-2398-656', max_length=50)),
                ('email', models.EmailField(default='you@chrislanduniversity.edu.ng', max_length=254)),
                ('passport', models.ImageField(blank=True, default='albinopin.jpg', upload_to='passport/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('co_authors', models.TextField(max_length=50)),
                ('journal_name', models.CharField(max_length=50)),
                ('publication_date', models.DateField(help_text='Date of Publication')),
                ('abstract', models.TextField(help_text='Enter the Abstract')),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(help_text='Has it been published?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mordi.staff')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('promotion_date', models.DateField(help_text='Promotion effective from..')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mordi.staff')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_theme', models.CharField(max_length=50)),
                ('organising_body', models.CharField(max_length=50)),
                ('conference_date', models.DateField(help_text='Date of conference/Seminar')),
                ('made_presentation', models.BooleanField()),
                ('abstract', models.TextField(help_text='Enter the Abstract')),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mordi.staff')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('co_authors', models.TextField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('chapter_title', models.CharField(blank=True, help_text='Optional', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mordi.staff')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
